CREATE TABLE IF NOT EXISTS contracts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,status VARCHAR(30) NOT NULL DEFAULT 'draft',title VARCHAR(200) NOT NULL DEFAULT '부동산(주거용)임대차계약서',
 property_address VARCHAR(300) NOT NULL,property_detail VARCHAR(300) DEFAULT '',floor_info VARCHAR(100) DEFAULT '',area_m2 DECIMAL(10,2) DEFAULT 0,use_type VARCHAR(100) DEFAULT '주거공간',
 deposit BIGINT NOT NULL DEFAULT 0,monthly_rent BIGINT NOT NULL DEFAULT 0,payment_day TINYINT DEFAULT NULL,rent_account VARCHAR(200) DEFAULT '',late_rate DECIMAL(5,2) DEFAULT 10.00,
 handover_date DATE NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,terms LONGTEXT NOT NULL,special_terms LONGTEXT,
 lessor_name VARCHAR(80) NOT NULL,lessor_birth VARCHAR(20) DEFAULT '',lessor_phone VARCHAR(30) NOT NULL,lessor_address VARCHAR(300) DEFAULT '',agent_name VARCHAR(80) DEFAULT '',agent_phone VARCHAR(30) DEFAULT '',
 lessee_name VARCHAR(80) NOT NULL,lessee_birth VARCHAR(20) DEFAULT '',lessee_phone VARCHAR(30) NOT NULL,lessee_address VARCHAR(300) DEFAULT '',
 lessor_token_hash CHAR(64) DEFAULT NULL,lessee_token_hash CHAR(64) DEFAULT NULL,token_expires_at DATETIME DEFAULT NULL,
 lessor_signed_at DATETIME DEFAULT NULL,lessee_signed_at DATETIME DEFAULT NULL,lessor_signature VARCHAR(255) DEFAULT NULL,lessee_signature VARCHAR(255) DEFAULT NULL,
 lessor_ip VARCHAR(45) DEFAULT NULL,lessee_ip VARCHAR(45) DEFAULT NULL,final_pdf VARCHAR(255) DEFAULT NULL,document_hash CHAR(64) DEFAULT NULL,
 created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,finalized_at DATETIME DEFAULT NULL,INDEX(status),INDEX(token_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,contract_id BIGINT UNSIGNED NOT NULL,actor_type VARCHAR(30) NOT NULL,action VARCHAR(80) NOT NULL,ip VARCHAR(45),user_agent VARCHAR(500),meta_json LONGTEXT,created_at DATETIME NOT NULL,INDEX(contract_id),CONSTRAINT fk_audit_contract FOREIGN KEY(contract_id) REFERENCES contracts(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sms_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,contract_id BIGINT UNSIGNED NOT NULL,recipient VARCHAR(30) NOT NULL,message TEXT NOT NULL,result_json LONGTEXT,created_at DATETIME NOT NULL,INDEX(contract_id),CONSTRAINT fk_sms_contract FOREIGN KEY(contract_id) REFERENCES contracts(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;