<?php
declare(strict_types=1);
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Referrer-Policy: no-referrer');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
header('Permissions-Policy: camera=(self), microphone=(), geolocation=()');
header("Content-Security-Policy: default-src 'self'; script-src 'self' https://cdn.jsdelivr.net 'wasm-unsafe-eval'; worker-src 'self' blob:; style-src 'self'; img-src 'self' blob: data:; connect-src 'self' https://cdn.jsdelivr.net https://tessdata.projectnaptha.com; font-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'");
?><!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Japan Entry Assistant | 일본 입국신고 도우미</title><link rel="stylesheet" href="assets/app.css"></head>
<body><main class="shell"><header class="hero"><span class="eyebrow">JAPAN ENTRY ASSISTANT</span><h1>일본 입국신고<br>스마트 도우미</h1><p>여권 정보를 브라우저에서 인식하고 여행 정보를 정리하세요. 공식 Visit Japan Web 등록은 직접 완료합니다.</p><div class="pill">🔒 서버 저장 없음 · 데이터베이스 불필요</div></header>
<nav class="steps" aria-label="진행 단계"><a href="#passport">01 여권</a><a href="#travel">02 여행정보</a><a href="#summary">03 확인·복사</a></nav>
<section class="card" id="passport"><div class="section-head"><span class="num">01</span><div><h2>여권 정보</h2><p>여권 사진 하단의 기계판독영역(MRZ)을 읽습니다.</p></div></div><div class="notice">여권 전체 사진을 인식할 수 있지만 <b>하단 영문 2줄(MRZ)이 선명한 사진</b>이 가장 정확합니다. 사진은 서버로 업로드하지 않습니다.</div><label class="upload" for="passportFile">📷 여권 촬영 / 사진 선택 <small>JPG·PNG·WEBP · 최대 12MB · 브라우저에서만 처리</small></label><input id="passportFile" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden><div id="ocrStatus" class="status" role="status">이미지를 선택하거나 아래에 직접 입력하세요.</div><div class="meter" id="meter" hidden><div id="meterFill"></div></div><details><summary>MRZ 두 줄을 직접 붙여넣기 (인식 실패 시)</summary><textarea id="mrzText" rows="3" placeholder="P<KOR...&#10;M123..." spellcheck="false"></textarea><button type="button" class="btn subtle" id="parseMrz">MRZ 분석</button></details><div class="fields two"><label>성 (Surname)<input id="surname" autocomplete="off" placeholder="KIM" data-uppercase></label><label>이름 (Given names)<input id="given" autocomplete="off" placeholder="GILDONG" data-uppercase></label><label>여권번호<input id="passportNo" autocomplete="off" placeholder="M12345678" data-uppercase></label><label>국적 (ISO 3자리)<input id="nationality" autocomplete="off" value="KOR" maxlength="3" data-uppercase></label><label>생년월일<input id="birth" type="date"></label><label>여권 만료일<input id="expiry" type="date"></label><label>성별<select id="sex"><option value="">선택</option><option value="M">남성 (M)</option><option value="F">여성 (F)</option><option value="X">기타/미표기</option></select></label><label>거주국가<input id="residence" value="REPUBLIC OF KOREA" autocomplete="off" data-uppercase></label></div><div id="mrzWarnings" class="warn" hidden></div></section>
<section class="card" id="travel"><div class="section-head"><span class="num">02</span><div><h2>여행 및 숙소</h2><p>영문 정보로 입력하면 공식 사이트에 옮기기 편합니다.</p></div></div><div class="row between"><p class="muted">여행마다 직접 입력하거나 예시 일정을 불러올 수 있습니다.</p><button class="btn subtle" type="button" id="loadSample">연수 일정 예시 불러오기</button></div><div class="fields two"><label>일본 도착일<input id="arrival" type="date"></label><label>항공사<input id="airline" placeholder="PARATA AIR" data-uppercase></label><label>항공편명 / 번호<input id="flight" placeholder="531" data-uppercase></label><label>일본 체류 예정일수<input id="stayDays" type="number" min="1" max="365" placeholder="예: 4"></label><label>도도부현 (Prefecture)<input id="prefecture" placeholder="HOKKAIDO" data-uppercase></label><label>시구정촌 (City)<input id="city" placeholder="NOBORIBETSU" data-uppercase></label><label>호텔명<input id="hotel" placeholder="HOTEL MAHOROBA" data-uppercase></label><label>우편번호<input id="postal" inputmode="numeric" placeholder="0590551" maxlength="7"></label><label class="wide">일본 체류지 주소<input id="address" placeholder="65 NOBORIBETSUONSENKOCHO, NOBORIBETSU, HOKKAIDO" data-uppercase></label><label>숙소 연락처<input id="hotelPhone" placeholder="+81 143-84-2111"></label><label>방문 목적<select id="purpose"><option value="BUSINESS">업무/연수 (BUSINESS)</option><option value="TOURISM">관광 (TOURISM)</option><option value="VISITING RELATIVES">친지 방문</option><option value="OTHER">기타</option></select></label></div><p class="muted tiny">※ 체류기간, 입국신고 질문, 세관신고 항목 등은 공식 사이트에서 실제 여행 상황에 맞게 입력하세요.</p></section>
<section class="card" id="summary"><div class="section-head"><span class="num">03</span><div><h2>확인 및 복사</h2><p>항목을 터치하면 해당 값만 복사할 수 있습니다.</p></div></div><div id="summaryList" class="summary-list"></div><div class="actions"><button class="btn primary" type="button" id="copyAll">📋 전체 정보 복사</button><button class="btn subtle" type="button" id="downloadTxt">⬇ TXT 내려받기</button><button class="btn danger" type="button" id="clearAll">🗑 입력정보 지우기</button></div><div class="notice"><b>개인정보 주의</b> 복사한 내용은 클립보드에, 내려받은 TXT는 기기에 남습니다. 공유 PC에서는 사용 후 반드시 삭제하세요.</div></section>
<section class="card"><div class="section-head"><span class="num">04</span><div><h2>공식 등록 완료하기</h2><p>이 앱은 정부 사이트와 연결된 자동 제출 서비스가 아닙니다.</p></div></div><ol class="checklist"><li><label><input type="checkbox"> 공식 Visit Japan Web 계정 생성 및 로그인</label></li><li><label><input type="checkbox"> 이용자 정보 등록 (여권 스캔 또는 수동 입력)</label></li><li><label><input type="checkbox"> 입국 예정 및 항공편·숙소 정보 등록</label></li><li><label><input type="checkbox"> 입국심사 및 세관신고 질문에 직접 답변</label></li><li><label><input type="checkbox"> 공식 QR코드 확인 및 출국 전 준비</label></li></ol><a class="btn primary full" href="https://www.vjw.digital.go.jp/" target="_blank" rel="noopener noreferrer">공식 Visit Japan Web 열기 ↗</a><p class="muted tiny">공식 서비스: 일본 디지털청 · 본 도우미는 비공식 서비스입니다.</p></section><footer>Japan Entry Assistant · Privacy-first · No server storage</footer></main><div id="toast" role="status" aria-live="polite"></div><script src="assets/app.js" defer></script></body></html>
