<?php
require_once __DIR__.'/lib/db.php';
$done=false;$err='';
if($_SERVER['REQUEST_METHOD']==='POST')try{
 $pdo=db();$exists=$pdo->query("SHOW TABLES LIKE 'admins'")->fetchColumn();if($exists)throw new RuntimeException('이미 설치된 DB입니다.');
 $sql=file_get_contents(__DIR__.'/schema.sql');foreach(array_filter(array_map('trim',explode(';',$sql))) as $q)$pdo->exec($q);
 $u=trim($_POST['username']);$p=$_POST['password'];$name=trim($_POST['name']);if(!$u||strlen($p)<8||!$name)throw new RuntimeException('관리자 정보와 8자 이상 비밀번호를 입력하세요.');
 $s=$pdo->prepare('INSERT INTO admins(username,password_hash,name,role) VALUES(?,?,?,?)');$s->execute([$u,password_hash($p,PASSWORD_DEFAULT),$name,'super_admin']);
 $defaults=['org_name'=>trim($_POST['org_name']),'grant_method'=>'fiscal','mandatory_rate'=>'70','daily_max_people'=>'2','request_months_ahead'=>'2','employee_auth_mode'=>'phone4','alimtalk_enabled'=>'0','allowance_monthly_hours'=>'209','allowance_daily_hours'=>'8','allowance_rounding'=>'1','ppurio_token_url'=>'https://message.ppurio.com/v1/token','ppurio_message_url'=>'https://message.ppurio.com/v1/kakao','notification_dispatch_mode'=>'immediate','notification_max_attempts'=>'3','notification_cron_key'=>bin2hex(random_bytes(32)),'notification_cron_last_run'=>'','notification_cron_last_result'=>''];foreach($defaults as $k=>$v)set_setting($k,$v);
 $pdo->exec("INSERT INTO departments(code,name,sort_order) VALUES('COMMON','공통',1)");
 $tpl=$pdo->prepare('INSERT INTO notification_templates(event_code,event_name,template_code,message_template,variable_help,sort_order) VALUES(?,?,?,?,?,?)');
 $samples=[['request','휴가 신청 결재요청','','#{var1}님의 #{var2} 신청입니다.\n기간: #{var3} ~ #{var4}\n사용일수: #{var5}일','var1 직원명, var2 휴가유형, var3 시작일, var4 종료일, var5 일수',10],['next_approval','다음 단계 결재요청','','#{var1}님의 휴가신청 결재 차례입니다.\n기간: #{var2} ~ #{var3}\n사용일수: #{var4}일','var1 직원명, var2 시작일, var3 종료일, var4 일수, var5 결재자',20],['approved','최종 승인 안내','','#{var1}님의 휴가신청이 승인되었습니다.\n기간: #{var2} ~ #{var3}\n사용일수: #{var4}일','var1 직원명, var2 시작일, var3 종료일, var4 일수, var5 휴가유형/의견',30],['rejected','반려 안내','','#{var1}님의 휴가신청이 반려되었습니다.\n기간: #{var2} ~ #{var3}\n사유: #{var5}','var1 직원명, var2 시작일, var3 종료일, var4 일수, var5 반려사유',40]];foreach($samples as $row)$tpl->execute($row);$done=true;
}catch(Throwable $e){$err=$e->getMessage();}
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/style.css"><title>설치</title></head><body><main class="install"><div class="card"><h1>HRM Plus 설치</h1><?php if($done):?><div class="alert ok">설치가 완료되었습니다.</div><a class="btn" href="admin/login.php">관리자 로그인</a><?php else:?><?php if($err):?><div class="alert err"><?=h($err)?></div><?php endif?><form method="post"><label>조직명<input name="org_name" required></label><label>최고관리자 이름<input name="name" required></label><label>아이디<input name="username" required></label><label>비밀번호(8자 이상)<input type="password" name="password" required></label><button class="btn">전체 DB 생성 및 설치</button></form><?php endif?></div></main></body></html>
