<?php
require_once __DIR__.'/lib/app.php';require_once __DIR__.'/lib/notify.php';
if(session_status()!==PHP_SESSION_ACTIVE)session_start();$pdo=db();$err='';
if(isset($_GET['logout'])){unset($_SESSION['employee_id']);header('Location: my.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['login'])){verify_csrf();$eid=(int)$_POST['employee_id'];$e=get_employee($eid);if(!$e)$err='직원정보를 확인하세요.';elseif(setting('employee_auth_mode','phone4')==='phone4' && substr(phone_clean($e['phone']),-4)!==trim($_POST['phone4']??''))$err='휴대폰 뒤 4자리가 일치하지 않습니다.';else{$_SESSION['employee_id']=$eid;header('Location: my.php');exit;}}
$emp=null;if(!empty($_SESSION['employee_id']))$emp=get_employee((int)$_SESSION['employee_id']);$employees=$pdo->query("SELECT id,name,position FROM employees WHERE is_active=1 ORDER BY sort_order,id")->fetchAll();
if(!$emp){?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/style.css"><title>개인 대시보드</title></head><body><main class="install"><div class="card"><h1>직원 개인 대시보드</h1><p class="muted">본인 확인 후 잔여연차와 신청현황을 확인합니다.</p><?php if($err):?><div class="alert err"><?=h($err)?></div><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="login" value="1"><label>직원<select name="employee_id" required><option value="">선택</option><?php foreach($employees as $e):?><option value="<?=$e['id']?>"><?=h($e['name'].' '.$e['position'])?></option><?php endforeach?></select></label><?php if(setting('employee_auth_mode','phone4')==='phone4'):?><label>휴대폰 뒤 4자리<input name="phone4" maxlength="4" inputmode="numeric" required></label><?php endif?><button class="btn">확인</button><a class="btn gray" href="index.php">신청화면</a></form></div></main></body></html><?php exit;}
$year=(int)($_GET['year']??date('Y'));$grant=grant_for_year($emp,$year);$used=used_for_year($emp['id'],$year,false);$pending=used_for_year($emp['id'],$year,true)-$used;$remain=$grant-$used;$rate=$grant>0?round($used/$grant*100,1):0;$mandatory=(float)($emp['mandatory_rate']!==null?$emp['mandatory_rate']:setting('mandatory_rate','70'));
$s=$pdo->prepare("SELECT lr.*,lt.name leave_name FROM leave_requests lr JOIN leave_types lt ON lt.id=lr.leave_type_id WHERE lr.employee_id=? ORDER BY lr.id DESC LIMIT 20");$s->execute([$emp['id']]);$rows=$s->fetchAll();
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/style.css"><title>개인 대시보드</title></head><body><header class="top"><div class="wrap"><div class="brand"><?=h(setting('org_name','휴가관리시스템'))?></div><nav class="nav"><a href="index.php">휴가신청</a><a href="my.php?logout=1">로그아웃</a></nav></div></header><main class="wrap"><div class="section-head"><div><h1><?=h($emp['name'].' '.$emp['position'])?> 개인 대시보드</h1><p class="muted"><?=$year?>년 기준</p></div><form><select name="year" onchange="this.form.submit()"><?php for($y=date('Y')+1;$y>=date('Y')-5;$y--):?><option <?=$year==$y?'selected':''?>><?=$y?></option><?php endfor?></select></form></div><div class="stats"><div class="stat"><span>부여연차</span><strong><?=fmt_days($grant)?>일</strong></div><div class="stat"><span>승인사용</span><strong><?=fmt_days($used)?>일</strong></div><div class="stat"><span>잔여연차</span><strong><?=fmt_days($remain)?>일</strong></div><div class="stat"><span>결재중</span><strong><?=fmt_days($pending)?>일</strong></div></div><div class="card"><h2>의무사용 현황</h2><div class="progress"><span style="width:<?=min(100,$rate)?>%"></span></div><p>현재 사용률 <strong><?=$rate?>%</strong> / 목표 <?=$mandatory?>%</p></div><div class="card"><h2>최근 신청내역</h2><table class="table"><tr><th>신청일</th><th>휴가유형</th><th>기간</th><th>일수</th><th>상태</th></tr><?php foreach($rows as $r):?><tr><td><?=h(substr($r['created_at'],0,10))?></td><td><?=h($r['leave_name'])?></td><td><?=h($r['start_date'])?><?=$r['start_date']!==$r['end_date']?' ~ '.h($r['end_date']):''?></td><td><?=fmt_days($r['requested_days'])?></td><td><span class="badge"><?=h(['in_approval'=>'결재중','approved'=>'승인','rejected'=>'반려','cancelled'=>'취소','pending'=>'대기'][$r['status']]??$r['status'])?></span><?php if($r['reject_reason']):?><div class="muted"><?=h($r['reject_reason'])?></div><?php endif?></td></tr><?php endforeach?></table></div></main></body></html>
