<?php
require dirname(__DIR__).'/config.php'; admin_required(); $d=load_data(); $msg=$_GET['m']??'';
?><!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>사진관리</title>
<style>
body{font-family:system-ui;background:#f4f6f9;margin:0;color:#172033}.w{max-width:980px;margin:auto;padding:20px}.card{background:#fff;padding:20px;border-radius:14px;margin-bottom:15px;border:1px solid #dde3ec}label{display:block;font-weight:800;margin-top:10px}input,select,textarea,button{width:100%;padding:11px;border:1px solid #cbd3df;border-radius:8px;box-sizing:border-box;margin-top:5px}textarea{min-height:85px}button{background:#172033;color:#fff;font-weight:800;cursor:pointer}.ok{background:#eaf8ee;padding:10px;border-radius:8px}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.item{display:grid;grid-template-columns:120px 1fr 190px;gap:12px;align-items:center;border-top:1px solid #eee;padding:12px 0}.item img{width:120px;height:90px;object-fit:cover;border-radius:8px}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.actions form{margin:0}.edit{background:#1f5eff}.del{background:#b42318}.editbox{display:none;grid-column:1/-1;background:#f7f9fc;border:1px solid #dce3ed;border-radius:12px;padding:14px}.editbox.open{display:block}.edit-actions{display:flex;gap:8px;margin-top:10px}.edit-actions button{width:auto}.cancel{background:#657083}.hash{font-size:11px;color:#657083;word-break:break-all;margin-top:8px}@media(max-width:650px){.row,.item{grid-template-columns:1fr}.item img{width:100%;height:auto}.actions{grid-template-columns:1fr 1fr}}
</style><main class="w">
<div class="card"><h1>현장사진 관리</h1><p><a href="../index.php">← 증거 정리 화면</a> · <a href="traffic.php">방문·트래픽 통계</a> · <a href="logout.php">로그아웃</a></p><?php if($msg):?><div class="ok"><?=h($msg)?></div><?php endif?></div>
<form class="card" method="post" action="upload.php" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><h2>사진 업로드</h2><div class="row"><div><label>SPOT</label><select name="spot" required><?php for($i=1;$i<=5;$i++):?><option value="<?=$i?>">SPOT <?=$i?></option><?php endfor?></select></div><div><label>촬영일시</label><input type="datetime-local" name="taken_at" value="<?=date('Y-m-d\TH:i')?>"></div></div><label>사진 선택 (여러 장 가능)</label><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple required><div class="row"><div><label>사진 제목</label><input name="title" placeholder="예: 334번지 하단 배수로 입구"></div><div><label>촬영 방향</label><input name="direction" placeholder="예: 북→남 / 350→334"></div></div><label>현장관찰 (사진에서 직접 확인되는 내용)</label><textarea name="observation"></textarea><label>입증취지 / 변론 메모</label><textarea name="purpose"></textarea><button>원본 사진 업로드</button><p>원본 파일은 서버에 보존하고 SHA-256 해시를 함께 기록합니다. 최대 <?=MAX_UPLOAD_MB?>MB/파일.</p></form>
<section class="card"><h2>등록 사진</h2>
<?php foreach(array_reverse($d['items']??[]) as $it): $eid='edit_'.preg_replace('/[^a-zA-Z0-9_-]/','',(string)$it['id']); ?>
<div class="item">
<img src="../<?=h($it['file'])?>">
<div><b>SPOT <?=h((string)$it['spot'])?> · <?=h($it['title']??'')?></b><br><?=h($it['taken_at']??'')?> · <?=h($it['direction']??'')?><br><small><?=h($it['observation']??'')?></small><?php if(!empty($it['purpose'])):?><br><small><b>입증취지:</b> <?=h($it['purpose'])?></small><?php endif?></div>
<div class="actions"><button type="button" class="edit" onclick="toggleEdit('<?=$eid?>')">설명 수정</button><form method="post" action="delete.php" onsubmit="return confirm('삭제할까요?')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="id" value="<?=h($it['id'])?>"><button class="del">삭제</button></form></div>
<form class="editbox" id="<?=$eid?>" method="post" action="update.php"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="id" value="<?=h($it['id'])?>">
<h3>사진 설명 수정</h3><div class="row"><div><label>SPOT</label><select name="spot"><?php for($i=1;$i<=5;$i++):?><option value="<?=$i?>" <?=$i==(int)$it['spot']?'selected':''?>>SPOT <?=$i?></option><?php endfor?></select></div><div><label>촬영일시</label><input type="datetime-local" name="taken_at" value="<?=h((string)($it['taken_at']??''))?>"></div></div>
<div class="row"><div><label>사진 제목</label><input name="title" value="<?=h($it['title']??'')?>"></div><div><label>촬영 방향</label><input name="direction" value="<?=h($it['direction']??'')?>"></div></div>
<label>현장관찰</label><textarea name="observation"><?=h($it['observation']??'')?></textarea><label>입증취지 / 변론 메모</label><textarea name="purpose"><?=h($it['purpose']??'')?></textarea>
<?php if(!empty($it['sha256'])):?><div class="hash">SHA-256: <?=h($it['sha256'])?> · 사진 자체는 수정되지 않습니다.</div><?php endif?>
<div class="edit-actions"><button type="submit">수정내용 저장</button><button type="button" class="cancel" onclick="toggleEdit('<?=$eid?>')">취소</button></div></form>
</div><?php endforeach?></section></main>
<script>function toggleEdit(id){var e=document.getElementById(id);if(!e)return;e.classList.toggle('open');if(e.classList.contains('open'))e.scrollIntoView({behavior:'smooth',block:'nearest'});}</script></html>