<?php
declare(strict_types=1);require_once dirname(__DIR__).'/config.php';require_once dirname(__DIR__).'/lib/common.php';require_once dirname(__DIR__).'/lib/customs.php';tp_admin_required();
$type=(string)($_GET['type']??'cargo');$no=trim((string)($_GET['no']??''));$year=(string)($_GET['year']??date('Y'));$err='';$result=null;
if($no!==''){try{$result=$type==='cargo'?tp_customs_lookup_cargo($no):tp_customs_lookup_bl($type,$no,$year);}catch(Throwable $e){$err=$e->getMessage();}}
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>관세청 API 테스트</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#f6f7f9}.wrap{max-width:1050px}.card{border:0;border-radius:16px}code{word-break:break-all}</style></head><body><div class="container wrap py-4"><h2 class="fw-bold">관세청 화물통관진행정보 API 테스트</h2><p class="text-secondary">v1.5 · API001 · cargMtNo / MBL / HBL 조회 및 다건목록 처리</p>
<div class="alert alert-info">해수부 <b>mrNum</b>은 MRN(적하목록 관리번호) 11자리이며 API001의 <b>cargMtNo 15~19자리와 다른 식별자</b>입니다. 임의 변환하지 않습니다.</div>
<form class="row g-2 mb-3"><div class="col-md-2"><select class="form-select" name="type"><option value="cargo" <?=$type==='cargo'?'selected':''?>>화물관리번호</option><option value="mbl" <?=$type==='mbl'?'selected':''?>>M B/L</option><option value="hbl" <?=$type==='hbl'?'selected':''?>>H B/L</option></select></div><div class="col-md-6"><input class="form-control" name="no" value="<?=h($no)?>" placeholder="cargMtNo 또는 B/L 번호"></div><div class="col-md-2"><input class="form-control" name="year" value="<?=h($year)?>" placeholder="입항년도"></div><div class="col-md-2"><button class="btn btn-dark w-100">조회</button></div></form>
<?php if($err):?><div class="alert alert-danger"><?=h($err)?></div><?php endif?>
<?php if($result):?><div class="alert alert-success">정상 응답 · 레코드수 <?=h((string)($result['count']??0))?> <?=!empty($result['notice'])?'· '.h($result['notice']):''?></div>
<?php $d=$result['detail']??(($result['product_name']??null)!==null?$result:[]); if($d):?><div class="card shadow-sm mb-3"><div class="card-body"><h5>상세 결과</h5><div class="row g-2 small"><div class="col-md-4"><b>화물관리번호</b><br><?=h($d['cargo_no']??'')?></div><div class="col-md-4"><b>품명</b><br><?=h($d['product_name']??'')?></div><div class="col-md-4"><b>진행상태</b><br><?=h($d['progress_status']??'')?></div><div class="col-md-4"><b>선박명</b><br><?=h($d['ship_name']??'')?></div><div class="col-md-4"><b>MBL / HBL</b><br><?=h(($d['mbl_no']??'').' / '.($d['hbl_no']??''))?></div><div class="col-md-4"><b>중량 / 포장</b><br><?=h((string)($d['total_weight']??''))?> <?=h($d['weight_unit']??'')?> / <?=h((string)($d['package_count']??''))?></div></div></div></div><?php endif?>
<?php $cs=$result['candidates']??[]; if($cs):?><div class="card shadow-sm"><div class="card-body"><h5>다건 후보 <?=count($cs)?>건</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>화물관리번호</th><th>MBL</th><th>HBL</th><th>입항일</th><th>선박</th><th>양륙항</th><th>선사</th></tr></thead><tbody><?php foreach($cs as $c):?><tr><td><code><?=h($c['cargo_no'])?></code></td><td><?=h($c['mbl_no'])?></td><td><?=h($c['hbl_no'])?></td><td><?=h($c['entry_date'])?></td><td><?=h($c['ship_name'])?></td><td><?=h($c['discharge_port'])?></td><td><?=h($c['shipping_company'])?></td></tr><?php endforeach?></tbody></table></div></div></div><?php endif?><?php endif?>
<a class="btn btn-outline-secondary mt-3" href="carriers.php">자동차운반선 후보</a> <a class="btn btn-outline-secondary mt-3" href="index.php">관리자로</a></div></body></html>
