<?php
require_once __DIR__.'/../lib/app.php';
$pageTitle='연차수당 계산'; include '_top.php';
$pdo=db(); $year=(int)($_GET['year']??$_POST['year']??date('Y')); $msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf(); $action=$_POST['action']??'calculate';
  if($action==='save_row'){
    $eid=(int)$_POST['employee_id']; $excluded=(float)($_POST['excluded_days']??0); $adjust=(float)($_POST['adjustment_days']??0);
    $s=$pdo->prepare('SELECT * FROM employees WHERE id=?');$s->execute([$eid]);$e=$s->fetch();
    if($e){$v=allowance_values($e,$year,$excluded,$adjust);$q=$pdo->prepare("INSERT INTO leave_allowance_calculations(employee_id,calc_year,monthly_ordinary_wage,monthly_standard_hours,daily_standard_hours,granted_days,used_days,excluded_days,adjustment_days,payable_unused_days,hourly_wage,daily_wage,allowance_amount,memo) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE monthly_ordinary_wage=VALUES(monthly_ordinary_wage),monthly_standard_hours=VALUES(monthly_standard_hours),daily_standard_hours=VALUES(daily_standard_hours),granted_days=VALUES(granted_days),used_days=VALUES(used_days),excluded_days=VALUES(excluded_days),adjustment_days=VALUES(adjustment_days),payable_unused_days=VALUES(payable_unused_days),hourly_wage=VALUES(hourly_wage),daily_wage=VALUES(daily_wage),allowance_amount=VALUES(allowance_amount),memo=VALUES(memo)");$q->execute([$eid,$year,$v['monthly'],$v['mh'],$v['dh'],$v['granted'],$v['used'],$excluded,$adjust,$v['payable'],$v['hourly'],$v['daily'],$v['amount'],trim($_POST['memo']??'')]);$msg='계산값을 저장했습니다.';}
  } elseif($action==='confirm'){
    $u=admin_user();$pdo->prepare('UPDATE leave_allowance_calculations SET is_confirmed=1,confirmed_at=NOW(),confirmed_by=? WHERE calc_year=?')->execute([$u['id'],$year]);$msg='해당 연도의 계산 결과를 확정했습니다.';
  } elseif($action==='unlock'){
    $pdo->prepare('UPDATE leave_allowance_calculations SET is_confirmed=0,confirmed_at=NULL,confirmed_by=NULL WHERE calc_year=?')->execute([$year]);$msg='확정을 취소했습니다.';
  } else {
    $emps=$pdo->query('SELECT * FROM employees WHERE allowance_enabled=1 ORDER BY sort_order,id')->fetchAll();
    foreach($emps as $e){$v=allowance_values($e,$year,0,0);$q=$pdo->prepare("INSERT INTO leave_allowance_calculations(employee_id,calc_year,monthly_ordinary_wage,monthly_standard_hours,daily_standard_hours,granted_days,used_days,excluded_days,adjustment_days,payable_unused_days,hourly_wage,daily_wage,allowance_amount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE monthly_ordinary_wage=IF(is_confirmed=1,monthly_ordinary_wage,VALUES(monthly_ordinary_wage)),monthly_standard_hours=IF(is_confirmed=1,monthly_standard_hours,VALUES(monthly_standard_hours)),daily_standard_hours=IF(is_confirmed=1,daily_standard_hours,VALUES(daily_standard_hours)),granted_days=IF(is_confirmed=1,granted_days,VALUES(granted_days)),used_days=IF(is_confirmed=1,used_days,VALUES(used_days)),payable_unused_days=IF(is_confirmed=1,payable_unused_days,GREATEST(0,VALUES(granted_days)-VALUES(used_days)-excluded_days+adjustment_days)),hourly_wage=IF(is_confirmed=1,hourly_wage,VALUES(hourly_wage)),daily_wage=IF(is_confirmed=1,daily_wage,VALUES(daily_wage)),allowance_amount=IF(is_confirmed=1,allowance_amount,ROUND(VALUES(daily_wage)*GREATEST(0,VALUES(granted_days)-VALUES(used_days)-excluded_days+adjustment_days)))");$q->execute([$e['id'],$year,$v['monthly'],$v['mh'],$v['dh'],$v['granted'],$v['used'],0,0,$v['payable'],$v['hourly'],$v['daily'],$v['amount']]);}
    $msg='전체 직원을 계산했습니다.';
  }
}
$s=$pdo->prepare("SELECT e.name,e.position,e.employee_no,d.name department_name,c.* FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN leave_allowance_calculations c ON c.employee_id=e.id AND c.calc_year=? WHERE e.allowance_enabled=1 ORDER BY e.sort_order,e.id");$s->execute([$year]);$rows=$s->fetchAll();
$total=array_sum(array_map(fn($r)=>(int)($r['allowance_amount']??0),$rows));
?>
<h1>연차수당 계산</h1>
<?php if($msg):?><div class="alert ok"><?=h($msg)?></div><?php endif?>
<div class="card no-print"><form method="get" class="inline-form"><label>기준연도 <input type="number" name="year" value="<?=$year?>"></label><button class="btn sm">조회</button></form><form method="post" class="actions"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="year" value="<?=$year?>"><button class="btn" name="action" value="calculate">전체 자동계산</button><button class="btn gray" name="action" value="confirm">전체 확정</button><button class="btn gray" name="action" value="unlock">확정 취소</button><button type="button" class="btn gray" onclick="window.print()">인쇄</button><a class="btn gray" href="allowances_csv.php?year=<?=$year?>">CSV</a></form></div>
<div class="card"><p class="muted">계산식: 월 통상임금 ÷ <?=h(setting('allowance_monthly_hours','209'))?>시간 × <?=h(setting('allowance_daily_hours','8'))?>시간 × 지급대상 미사용일수</p><table class="table"><tr><th>직원</th><th>월 통상임금</th><th>부여</th><th>사용</th><th>제외/조정</th><th>지급일수</th><th>1일 통상임금</th><th>예상수당</th><th>상태</th></tr><?php foreach($rows as $r):?><tr><td><?=h($r['name'].' '.$r['position'])?><div class="muted"><?=h($r['department_name'])?></div></td><td><?=number_format((int)($r['monthly_ordinary_wage']??0))?></td><td><?=fmt_days($r['granted_days']??0)?></td><td><?=fmt_days($r['used_days']??0)?></td><td><form method="post" class="mini-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="employee_id" value="<?=$r['employee_id']??''?>"><input type="number" step=".25" name="excluded_days" value="<?=h($r['excluded_days']??0)?>" title="수당 제외일수"><input type="number" step=".25" name="adjustment_days" value="<?=h($r['adjustment_days']??0)?>" title="조정일수"><input type="hidden" name="memo" value="<?=h($r['memo']??'')?>"><button class="btn sm" name="action" value="save_row" <?=($r['is_confirmed']??0)?'disabled':''?>>저장</button></form></td><td><?=fmt_days($r['payable_unused_days']??0)?></td><td><?=number_format((int)round($r['daily_wage']??0))?></td><td><strong><?=number_format((int)($r['allowance_amount']??0))?>원</strong></td><td><?=($r['is_confirmed']??0)?'<span class="badge">확정</span>':'계산중'?></td></tr><?php endforeach?><tfoot><tr><th colspan="7">합계</th><th><?=number_format($total)?>원</th><th></th></tr></tfoot></table></div>
<?php include '_bottom.php';?>
